upgrade to debian:buster

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -1,28 +1,22 @@
 #!/bin/bash
 
-logfile=/var/log/docker-aptly.log
-
-log() {
-	ts=$(date "+[%Y:%m:%d %H:%M:%S]")
-	echo>>$logfile "$ts $@"
-}
+. /usr/local/bin/common
 
 function f_greprepo() {
-	aptly repo list -raw|grep -E "^$1$"
+	repo list -raw|grep -E "^$1$"
 }
 
 function f_greppublished() {
-	aptly publish list -raw|cut -d' ' -f2|grep -E "^$1$"
+	publish list -raw|cut -d' ' -f2|grep -E "^$1$"
 }
 
 function f_repocheck() {
 	dist=$1
-	if [ -z "$(f_greprepo $dist)" ]; then
-		if [ "$AUTO_CREATE_REPO" = "true" ]; then
-			repo-create>&2 2>/dev/null $dist
+	if [ -z "$(f_greprepo ${dist})" ]; then
+		if [ "${AUTO_CREATE_REPO}" = "true" ]; then
+			repo create "${dist}"
 		else
-			echo>&2 "[aptly] error: trying to add package to non-existing repo $dist"
-			log "error: trying to add package to non-existing repo $dist"
+			log "error: trying to add package to non-existing repo ${dist}"
 			echo err
 		fi
 	fi
@@ -32,65 +26,68 @@ function f_publish() {
 	dist=$1
 	sname=$2
 
-	if [ -z "$(f_greppublished $dist)" ]; then
-		publish snapshot $sname
+	if [ -z "$(f_greppublished ${dist})" ]; then
+		publish snapshot "${sname}"
 	else
-		publish switch $dist $sname
+		publish switch "${dist}" "${sname}"
 	fi
+	return $?
 }
 
 function f_process() {
 	path=$1
-	filename=$(basename $path)
+	filename=$(basename "${path}")
 	ext="${filename##*.}"
-	if [ "$ext" = "deb" ]; then
-		dist=$(basename $(dirname $path))
-		state=$(f_repocheck $dist)
-		if [ -z "$state" ]; then
-			if [ ! -f debs/$dist/$filename ]; then
-				if aptly repo add $dist $path; then
-					sname=$dist-$(date '+%Y%m%d_%s')-$RANDOM
+	if [ "${ext}" = "deb" ]; then
+		dist=$(basename $(dirname ${path}))
+		state=$(f_repocheck "${dist}")
+		if [ -z "${state}" ]; then
+			if [ ! -f "debs/${dist}/${filename}" ]; then
+				if repo add "${dist}" "${path}"; then
+					sname="${dist}-$(date '+%Y%m%d_%s')-${RANDOM}"
 
-					aptly snapshot create $sname from repo $dist
-					f_publish $dist $sname
-					[ ! -d debs/$dist ] && mkdir -p debs/$dist
-					cp $path debs/$dist/$filename
-					log "info: published debs/$dist/$filename"
+					if snapshot create "${sname}" from repo "${dist}"; then
+						if f_publish "${dist}" "${sname}"; then
+							[ ! -d "debs/${dist}" ] && mkdir -p "debs/${dist}"
+							cp "${path}" "debs/${dist}/${filename}"
+							log "info: published debs/${dist}/${filename}"
+						fi
+					fi
 				fi
 			else
-				echo>&2 "[aptly] warning: this package already exists"
-				log "warning: this package already exists (debs/$dist/$filename)"
+				log "warning: this package already exists (debs/${dist}/${filename})"
 			fi
 		fi
 	else
-		echo>&2 "[aptly] error: ignoring file $filename (bad extension: $ext)"
-		log "error: ignoring file $filename (bad extension: $ext)"
+		log "error: ignoring file ${filename} (bad extension: ${ext})"
 	fi
-	rm -f $path												# remove file
-	rmdir $(dirname $path)						# remove supposedly dist
-	rmdir $(dirname $(dirname $path)) # remove temporary created dir
+	rm -f "${path}"												# remove file
+	rmdir "$(dirname ${path})"						# remove supposedly dist
+	rmdir "$(dirname $(dirname ${path}))" # remove temporary created dir
 }
 
 if [ ! -r private.key ]; then
-	echo>&2 "[aptly] fatal error: no private.key file"
 	log "fatal error: no private.key file"
 	exit 1
 fi
 
-gpg --no-tty --import private.key
-grep -q 'no-tty' ~/.gnupg/gpg.conf||echo>> ~/.gnupg/gpg.conf 'no-tty'
+if gpg1 --batch --no-tty --import private.key; then
+	grep -q 'no-tty' ~/.gnupg/gpg.conf||echo>>~/.gnupg/gpg.conf 'no-tty'
+else
+	log "fatal error: cannot import private.key file"
+	exit 1
+fi
 
-[ -n "$PASSPHRASE" ] && echo>passphrase "$PASSPHRASE"
+[ -n "${PASSPHRASE}" ] && echo>passphrase "${PASSPHRASE}"
 if [ ! -r passphrase ]; then
-	echo>&2 "[aptly] fatal error: no passphrase"
 	log "fatal error: no passphrase"
-	exit 2
+	exit 1
 fi
 
 chown root: passphrase
 chmod 000 passphrase
 
 inotifywait -rme CLOSE_WRITE --format '%w%f' /shared|while read line; do
-	log "info: CLOSE_WRITE $line"
-	f_process $line
+	log "info: CLOSE_WRITE ${line}"
+	f_process "${line}"
 done
